### ISSUE TITLE
Crash when setting DB size to 1KB

### ISSUE THREAD

**Issue by terror** [cberner/redb#159]
Hey Chris! I'm currently working `ord` with Casey and we ran into this crash when setting the database size to 1KiB: 

```
---- index::foo stdout ----
0.0: 0396bc915f141f7de025f72ae9b6bb8dcdb5f444fc245d8fac486ba67a38eef9
thread 'index::foo' panicked at 'Test failed: exit status: 101
thread 'main' panicked at 'assertion failed: largest_order_in_pages > 0', /Users/liam/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.0.4/src/tree_store/page_store/page_manager.rs:434:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/core/src/panicking.rs:48:5
   3: redb::tree_store::page_store::page_manager::TransactionalMemory::new
   4: redb::tree_store::storage::Storage::new
   5: redb::db::Database::open
   6: ord::index::Index::new
   7: ord::command::find::Find::run
   8: ord::command::Arguments::run
   9: ord::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
', tests/integration.rs:124:7
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/core/src/panicking.rs:107:14
   2: integration::Test::output
   3: integration::index::foo
   4: core::ops::function::FnOnce::call_once
   5: core::ops::function::FnOnce::call_once
             at /rustc/2885c474823637ae69c5967327327a337aebedb2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

More specifically, when we set the database size to anything less than 40KiB we get this crash, otherwise we get a useful error message.

**Comment by cberner** [comment]
Thanks! Ya, I should make a better error message for that. There's a lower bound on supported db size, but it just asserts it, as you can see :)
