### ISSUE TITLE
resize_db test crashes on macos

### ISSUE THREAD

**Issue by casey** [cberner/redb#187]
The `resize_db` test fails on my machine, backtrace below. I haven't had a chance to dig into it, so I have no idea what's going wrong. I see that CI runs on macos, so maybe the fact that I'm using an arm mac has something to do with it.

```
---- resize_db stdout ----
thread 'resize_db' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 7, error_len: Some(1) }', src/types.rs:89:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: <str as redb::types::RedbValue>::from_bytes
             at ./src/types.rs:89:9
   5: <str as redb::types::RedbKey>::compare
             at ./src/types.rs:104:20
   6: redb::tree_store::btree_base::InternalAccessor<T>::child_for_key
             at ./src/tree_store/btree_base.rs:400:19
   7: redb::tree_store::btree_utils::tree_insert_helper
             at ./src/tree_store/btree_utils.rs:934:45
   8: redb::tree_store::btree_utils::tree_insert
             at ./src/tree_store/btree_utils.rs:710:32
   9: redb::tree_store::storage::Storage::insert
             at ./src/tree_store/storage.rs:423:40
  10: redb::tree_store::storage::Storage::process_freed_pages
             at ./src/tree_store/storage.rs:594:32
  11: redb::tree_store::storage::Storage::commit
             at ./src/tree_store/storage.rs:493:13
  12: redb::db::DatabaseTransaction::commit_helper_inner
             at ./src/db.rs:377:13
  13: redb::db::DatabaseTransaction::commit_helper
             at ./src/db.rs:348:15
  14: redb::db::DatabaseTransaction::commit
             at ./src/db.rs:338:9
  15: integration_tests::resize_db
             at ./tests/integration_tests.rs:184:5
  16: integration_tests::resize_db::{{closure}}
             at ./tests/integration_tests.rs:132:1
  17: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cberner** [comment]
Can you try with a commit after `83d3ece94febd22254695fc83bc23874920005f1`, if you haven't already? I think it's unlikely that this is the issue, but I did make a change in that resize_db code path because it was assuming that `usize` was 8 bytes.

**Comment by casey** [comment]
Just tested it, and got the same crash. Looking at the stack trace, <str as RedbValue>::from_bytes seems to be the offending function. I added `dbg!(data)`, and the last value that gets printed out before the crash is `[0, 0, 0, 0, 0, 0, 0, 199, 0, 0, 0, 0, 0, 0, 0, 0]`, which is a valid UTF-8 string (nulls) up until the 199. Not sure if that helps or not, since it the unicode conversion failure might be a red herring, and the problem is corruption somewhere else.

**Comment by cberner** [comment]
Ya, that's almost certainly a red herring. Presumably the file has gotten corrupted by the expansion, and it doesn't show up until you try to read that data. I'll see if I can reproduce it on my raspberry pi

**Comment by cberner** [comment]
Ah! It's a bug when using pages != 4k. I'll take a look

**Comment by cberner** [comment]
Turns out the bug isn't Mac specific. My testing of resize just wasn't very good, so the test only happened to fail with 16k pages =P
