### ISSUE TITLE
Hit unreachable code

### ISSUE THREAD

**Issue by casey** [cberner/redb#318]
I have a test in a [branch](https://github.com/casey/ord/tree/redb-unreachable) which triggers an internal error one out of every four or five times it runs:

```
running 2 tests
test find::first_satoshi_of_second_block ... thread '<unnamed>' panicked at 'internal error: entered unreachable code', /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs:280:18
stack backtrace:
thread 'main' panicked at 'internal error: entered unreachable code', /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs:280:18
stack backtrace:
      00: : rust_begin_unwind
             at rust_begin_unwind/rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs
:             at 584/rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs::5584
:5
   1: core::panicking::panic_fmt
               at  /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:141: core
::panicking::panic_fmt
             at  /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs : 1422:: 14core
::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
   3: redb::tree_store::btree::Btree<K,V > :: get_helper3
:              at redb/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs:::tree_store280:::btree18::
Btree<K,V>::get_helper
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs:280:18
     4 : 4redb: ::redbtree_store::::tree_storebtree::::btreeBtree::<BtreeK<,KV,>V::>get::
get             at
/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs             at :/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs255::25523:
23
    5 :  redb5::: tree_storeredb::::btreetree_store::::BtreeMutbtree::<BtreeMutK<,KV,>V::>get::
get             at
/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs             at :/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/btree.rs152::1529:
9
   6: redb::tree_store::table_tree::TableTree::get_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/table_tree.rs:329:39
   7: redb::tree_store::table_tree::TableTree::get_or_create_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/table_tree.rs:396:30
   6: redb::tree_store::table_tree::TableTree::get_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/table_tree.rs:329:39
   7: redb::tree_store::table_tree::TableTree::get_or_create_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/tree_store/table_tree.rs:396:30
   8 :  redb ::8transactions: ::WriteTransactionredb::::open_tabletransactions
::             at WriteTransaction/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/transactions.rs:::open_table160
:             at 30
/Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.4.0/src/transactions.rs:160:30
   9: ord::index::Index::open
              at  /Users/rodarmor/src/ord/src/index.rs :941: :ord5::
index::Index::index_block
             at /Users/rodarmor/src/ord/src/index.rs : 12110:: 30ord
::index::Index::index
             at /Users/rodarmor/src/ord/src/index.rs:51 : 1710
: ord::index::Index::index_ranges
             at /Users/rodarmor/src/ord/src/index.rs:108:18
  11: ord::subcommand::find::Find::run
             at /Users/rodarmor/src/ord/src/subcommand/find.rs:10:17
  12: ord::subcommand::Subcommand::run
             at /Users/rodarmor/src/ord/src/subcommand.rs:39:27
  13: ord::arguments::Arguments::run
             at /Users/rodarmor/src/ord/src/arguments.rs:14:5
  11: ord::subcommand::server::Server::run::{{closure}}::{{closure}}
             at /Users/rodarmor/src/ord/src/subcommand/server.rs:56:29
  14: ord::main
             at /Users/rodarmor/src/ord/src/main.rs:102:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  15: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILED
test find::first_satoshi_of_second_block_slot ... ignored

failures:

---- find::first_satoshi_of_second_block stdout ----
thread 'main' panicked at 'Test failed: exit status: 101
stdout:

stderr:
', tests/test.rs:152:7
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: integration::test::Test::output
             at ./tests/test.rs:152:7
   3: integration::test::Test::run
             at ./tests/test.rs:109:5
   4: integration::find::first_satoshi_of_second_block
             at ./tests/find.rs:42:3
   5: integration::find::first_satoshi_of_second_block::{{closure}}
             at ./tests/find.rs:41:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by casey** [comment]
I think this has to do with the 1 MiB default index size that we're using for tests. If I bump the max index size to 10 MiB I don't hit this error.

**Comment by casey** [comment]
Jk, I'm still getting this error even with the bumped index size.

**Comment by cberner** [comment]
That branch of ord doesn't build because the dust-limit branch is missing from https://github.com/terror/bdk

Can I use master of that repo?

**Comment by cberner** [comment]
Nope, apparently not :) lemme know when you get a chance to update your branch and I'll take a look. I fixed at least one data corruption bug on master of redb, but I think it manifests as an index out of bounds and not a panic on unreachable code

**Comment by casey** [comment]
Whoops, that branch went away briefly, but it's back now.

**Comment by casey** [comment]
For reference, the command I'm running is:

```
RUST_BACKTRACE=1 cargo test --test integration -- find::first_satoshi_of_second_block
```

**Comment by casey** [comment]
Hmmm, on `master` I'm getting `error: Database already open. Cannot acquire lock.` I think I may be opening the database twice in my tests T_T. At least I requested the feature that saves me from this.

**Comment by casey** [comment]
Okay, yup that was it. This can be closed as wontfix PEBCAK.
