### ISSUE TITLE
Hit debug assertion in TransactionalMemory::get_page

### ISSUE THREAD

**Issue by casey** [cberner/redb#334]
I don't think I'm doing anything weird, like opening the database twice, but you never know. [This branch](https://github.com/casey/ord/tree/redb-debug-assert) is hitting the debug assertion in this function:

```
    pub(crate) fn get_page(&self, page_number: PageNumber) -> PageImpl {
        // We must not retrieve an immutable reference to a page which already has a mutable ref to it
        #[cfg(debug_assertions)]
        debug_assert!(
            !self.open_dirty_pages.lock().unwrap().contains(&page_number),
            "{:?}",
            page_number
        );
```

When I run `cargo test --test integration -- server::outputs`. It's bottoming out in this function:

```
  pub(crate) fn height(&self) -> Result<u64> {
    let tx = self.database.begin_read()?;

    let height_to_hash = tx.open_table(HEIGHT_TO_HASH)?;

    Ok(
      height_to_hash
        .range(0..)?
        .rev()
        .next()
        .map(|(height, _hash)| height + 1)
        .unwrap_or(0),
    )
  }
```

Which is being called repeatedly, but, I don't think concurrently.

```
   Compiling ord v0.0.3 (/Users/rodarmor/src/ord)
    Finished test [unoptimized + debuginfo] target(s) in 2.85s
     Running tests/main.rs (target/debug/deps/integration-30aaec0c2a76a9ac)

running 1 test
thread 'tokio-runtime-worker' panicked at 'r0.9/0', /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/page_store/page_manager.rs:925:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: redb::tree_store::page_store::page_manager::TransactionalMemory::get_page
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/page_store/page_manager.rs:925:9
   3: redb::tree_store::btree::Btree<K,V>::get
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/btree.rs:256:29
   4: redb::tree_store::btree::BtreeMut<K,V>::get
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/btree.rs:154:9
   5: redb::tree_store::table_tree::TableTree::get_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/tree_store/table_tree.rs:329:39
   6: redb::transactions::ReadTransaction::open_table
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.5.0/src/transactions.rs:515:22
   7: ord::index::Index::height
             at /Users/rodarmor/src/ord/src/index.rs:240:26
   8: ord::subcommand::server::Server::height::{{closure}}
             at /Users/rodarmor/src/ord/src/subcommand/server.rs:359:36
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  10: <F as axum::handler::Handler<(T1,),B>>::call::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.15/src/handler/mod.rs:250:45
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  13: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/map.rs:55:37
  14: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/lib.rs:91:13
  15: <axum::handler::future::IntoServiceFuture<F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.15/src/macros.rs:42:17
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  17: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  18: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.15/src/routing/route.rs:150:61
  19: <tower_http::map_response_body::ResponseFuture<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.4/src/map_response_body.rs:204:26
  20: <tower_http::map_response_body::ResponseFuture<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.4/src/map_response_body.rs:204:26
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  22: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  23: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.15/src/routing/route.rs:150:61
  24: <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.4/src/cors/mod.rs:662:56
  25: <tower_http::map_response_body::ResponseFuture<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.4/src/map_response_body.rs:204:26
  26: <tower_http::map_response_body::ResponseFuture<Fut,F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.4/src/map_response_body.rs:204:26
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  28: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  29: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.15/src/routing/route.rs:150:61
  30: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:491:35
  31: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:297:43
  32: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:161:21
  33: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:137:16
  34: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:120:28
  35: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:424:9
  36: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/conn.rs:952:47
  37: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/conn.rs:1012:30
  38: axum_server::server::Server<A>::serve::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/select.rs:507:49
  39: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/future/poll_fn.rs:38:9
  40: axum_server::server::Server<A>::serve::{{closure}}::{{closure}}::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-server-0.4.2/src/server.rs:203:25
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  42: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  43: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  45: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  46: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  47: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  48: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  49: ___rust_try
  50: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  51: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  52: tokio::runtime::task::harness::poll_future
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  55: tokio::runtime::task::raw::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  57: tokio::runtime::task::LocalNotified<S>::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:381:9
  58: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:435:13
  59: tokio::coop::with_budget::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  60: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  61: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  62: tokio::coop::with_budget
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  63: tokio::coop::budget
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  64: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
  65: tokio::runtime::thread_pool::worker::Context::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:401:24
  66: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:386:17
  67: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  68: tokio::runtime::thread_pool::worker::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:383:5
  69: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:362:45
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/task.rs:42:21
  71: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  77: ___rust_try
  78: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  79: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  80: tokio::runtime::task::harness::poll_future
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  83: tokio::runtime::task::raw::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:418:9
  86: tokio::runtime::blocking::pool::Task::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:91:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:325:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/rodarmor/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test server::outputs ... FAILED

failures:

---- server::outputs stdout ----
thread 'server::outputs' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(58875), path: "/height", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) }', tests/state.rs:258:8
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1098:23
   4: integration::state::State::request_expected
             at ./tests/state.rs:254:24
   5: integration::state::State::request
             at ./tests/state.rs:202:5
   6: integration::server::outputs
             at ./tests/server.rs:186:3
   7: integration::server::outputs::{{closure}}
             at ./tests/server.rs:173:1
   8: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    server::outputs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 67 filtered out; finished in 11.91s

error: test failed, to rerun pass '--test integration'
[Finished running. Exit status: 101]
git p^C2022-08-11T16:59:38.853-07:00 - WARN - Could not pass on signal to command: I/O error: No such process (os error 3)
```

**Comment by cberner** [comment]
Well, that's not good. I haven't seen an error like that in a while. What do I need to do to setup bitcoind to run that test? I downloaded the binary and added it to my PATH, but the test fails with:
```
Error serving request for transaction with txid 30b037a346d31902f146a53d9ac8fa90541f43ca4a5e321914e86acdbf28394c: JSON-RPC error: RPC error response: RpcError { code: -5, message: "No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.", data: None }
```

**Comment by casey** [comment]
Ah, you need the `-txindex=1`. I have that in my config locally, I'll update the test. Bitcoind normally doesn't maintain a lookup table from txid to transaction, so can't server requests for random transactions.

**Comment by cberner** [comment]
With that flag it fails on a whitespace difference:
```
---- server::outputs stdout ----
thread 'server::outputs' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<<ul>
<  <li><a href='/output/30b037a346d31902f146a53d9ac8fa90541f43ca4a5e321914e86acdbf28394c:0'>30b037a346d31902f146a53d9ac8fa90541f43ca4a5e321914e86acdbf28394c:0</a></li>
<</ul>
>
>    <ul>
>      <li><a href='/output/30b037a346d31902f146a53d9ac8fa90541f43ca4a5e321914e86acdbf28394c:0'>30b037a346d31902f146a53d9ac8fa90541f43ca4a5e321914e86acdbf28394c:0</a></li>
>    </ul>
>    

', tests/expected.rs:17:31
stack backtrace:
   0:     0x55a4678508bd - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a4678508bd - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a4678508bd - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a4678508bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a46787782c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55a467849861 - std::io::Write::write_fmt::h323ab2482abeeec6
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55a467852365 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a467852365 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a467852365 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55a467852009 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:311:9
  10:     0x55a4678528f6 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x55a4678527e7 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x55a467850d74 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a467852519 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x55a46691eb73 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x55a46695d429 - integration::expected::Expected::assert_match::h26e17f75a1aeb62f
                               at /home/cberner/Code/ord/tests/expected.rs:17:31
  16:     0x55a466a03a79 - integration::state::State::request_expected::heca5ace24434b6b3
                               at /home/cberner/Code/ord/tests/state.rs:287:5
  17:     0x55a466a02577 - integration::state::State::request::h21fe93d7e2c31959
                               at /home/cberner/Code/ord/tests/state.rs:203:5
  18:     0x55a466a638d5 - integration::server::outputs::hf497fd0d2aa743bd
                               at /home/cberner/Code/ord/tests/server.rs:186:3
  19:     0x55a46695ce6a - integration::server::outputs::{{closure}}::h236da491a9eaeea5
                               at /home/cberner/Code/ord/tests/server.rs:173:1

```

And if I comment out line 287 in state.rs it always passes (5 out of 5 so far). How reliably does it fail for you?

**Comment by casey** [comment]
Pretty reliably, I just ran it 6 times, and it only passed once. I just fixed the whitespace, so it should pass if it doesn't hit the assert.

**Comment by casey** [comment]
I can try to work on a more minimal reproduction. There's definitely a race condition in there which I imagine might make it not trigger.

**Comment by cberner** [comment]
Ah, interesting. I can reproduce it if I set my page size to 16kb. I guess as a workaround you might be able to use `DatabaseBuilder::set_page_size(4096)`. Leaving on vacation for a week, tomorrow, so it may be a bit before I fix this one

**Comment by casey** [comment]
Nice, I'll try that. Have fun on vacation!

**Comment by cberner** [comment]
Thanks! Fix turned out to be pretty easy. #335 should fix this :)

**Comment by casey** [comment]
Nice, just tested the branch and it fixes the issue!

**Comment by casey** [comment]
Maybe there should be some kind of stress test that a bunch of crazy reads from different threads at the same time? Also maybe some tests w/nonstandard page sizes?

**Comment by cberner** [comment]
Ya, nonstandard page sizes would be easy to add to the fuzzer. Stress test is probably a good idea, although spending time auditing the unsafe code might be higher yield. When I read the `Safety:` comment on that code, it was obviously wrong =P
