### ISSUE TITLE
Getting 'assertion failed: order <= self.get_max_order()'

### ISSUE THREAD

**Issue by hantuzun** [cberner/redb#519]
I was running `ord index` with https://github.com/casey/ord/tree/fdb13962e4bb5d0e2e35107fdfb3e0295ced02fd (redb 0.13.0). My macOS with Xeon crashed and when I run the index command again I get the following redb assertion error:

```
$ RUST_BACKTRACE=full ord --first-inscription-height 767430 --height-limit 775230 index

thread 'main' panicked at 'assertion failed: order <= self.get_max_order()', /Users/han/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/buddy_allocator.rs:367:9
stack backtrace:
   0:        0x100ed3286 - std::backtrace_rs::backtrace::libunwind::trace::h310cbd77a7d2ae59
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100ed3286 - std::backtrace_rs::backtrace::trace_unsynchronized::h5768bae568840507
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100ed3286 - std::sys_common::backtrace::_print_fmt::hd104a205649a2ffb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x100ed3286 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h521420ec33f3769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100ef454a - core::fmt::write::h694a0d7c23f57ada
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:        0x100ecc6bc - std::io::Write::write_fmt::h1920a3973ad439e5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:        0x100ed306a - std::sys_common::backtrace::_print::h75582c4ed1a04abb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x100ed306a - std::sys_common::backtrace::print::hef1aa4dbdc07ee06
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x100ed4c93 - std::panicking::default_hook::{{closure}}::h529701a1070b4ce0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:        0x100ed49e8 - std::panicking::default_hook::hfeeab2c667b2d7c2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:        0x100ed53c3 - std::panicking::rust_panic_with_hook::h1b5245192f90251d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:        0x100ed5153 - std::panicking::begin_panic_handler::{{closure}}::h3658f3a9566379d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:577:13
  12:        0x100ed3728 - std::sys_common::backtrace::__rust_end_short_backtrace::h9e01645d962f8882
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x100ed4e5d - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:        0x100f26c13 - core::panicking::panic_fmt::h0097ad8ec0b07517
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:        0x100f26ce7 - core::panicking::panic::ha47a4f67bad0ba2d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
  16:        0x100cdc91c - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  17:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  18:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  19:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  20:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  21:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  22:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  23:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  24:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  25:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  26:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  27:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  28:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  29:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  30:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  31:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  32:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  33:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  34:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  35:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  36:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  37:        0x100cdc84d - redb::tree_store::page_store::buddy_allocator::BuddyAllocatorMut::record_alloc::h499c7c418a569be5
  38:        0x100cf8838 - redb::tree_store::page_store::page_manager::TransactionalMemory::mark_pages_allocated::h3a98f027388bc4d3
  39:        0x100cda607 - redb::db::Database::new::hf79b01edd109b852
  40:        0x100738cd9 - redb::db::Builder::open_mmapped::ha4414c39c49df8bd
  41:        0x100a57381 - ord::index::Index::open::h9cc6f2081b376cdb
  42:        0x1007b4ef2 - ord::subcommand::index::run::h74a10a8980533b0d
  43:        0x100a00847 - ord::subcommand::Subcommand::run::hac8bca658950d312
  44:        0x1008d1486 - ord::main::ha767843f454048d8
  45:        0x1006fdcb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::he7c5919472da9bc8
  46:        0x1006fdc8c - std::rt::lang_start::{{closure}}::h7c949b917fc708c3
  47:        0x100ec6364 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2302f1d25ef2ca9b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  48:        0x100ec6364 - std::panicking::try::do_call::h6695e32a593de2cc
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  49:        0x100ec6364 - std::panicking::try::hd4a93095627721a9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  50:        0x100ec6364 - std::panic::catch_unwind::he41b3dba63feca94
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  51:        0x100ec6364 - std::rt::lang_start_internal::{{closure}}::hbf45583011495a61
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  52:        0x100ec6364 - std::panicking::try::do_call::ha3e6b3edab7da449
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  53:        0x100ec6364 - std::panicking::try::hd4e0f354bf7022b9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  54:        0x100ec6364 - std::panic::catch_unwind::h1035b163871a4269
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  55:        0x100ec6364 - std::rt::lang_start_internal::hd56d2fa7efb2dd60
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  56:        0x1006fdcfc - _main
  57:     0x7ff816e81310 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/han/.cargo/registry/src/github.com-1ecc6299db9ec823/redb-0.13.0/src/tree_store/page_store/page_manager.rs:1420:43
stack backtrace:
   0:        0x100ed3286 - std::backtrace_rs::backtrace::libunwind::trace::h310cbd77a7d2ae59
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100ed3286 - std::backtrace_rs::backtrace::trace_unsynchronized::h5768bae568840507
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100ed3286 - std::sys_common::backtrace::_print_fmt::hd104a205649a2ffb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x100ed3286 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h521420ec33f3769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x100ef454a - core::fmt::write::h694a0d7c23f57ada
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:        0x100ecc6bc - std::io::Write::write_fmt::h1920a3973ad439e5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:        0x100ed306a - std::sys_common::backtrace::_print::h75582c4ed1a04abb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x100ed306a - std::sys_common::backtrace::print::hef1aa4dbdc07ee06
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x100ed4c93 - std::panicking::default_hook::{{closure}}::h529701a1070b4ce0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:        0x100ed49e8 - std::panicking::default_hook::hfeeab2c667b2d7c2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:        0x100ed53c3 - std::panicking::rust_panic_with_hook::h1b5245192f90251d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:        0x100ed5194 - std::panicking::begin_panic_handler::{{closure}}::h3658f3a9566379d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:579:13
  12:        0x100ed3728 - std::sys_common::backtrace::__rust_end_short_backtrace::h9e01645d962f8882
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x100ed4e5d - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:        0x100f26c13 - core::panicking::panic_fmt::h0097ad8ec0b07517
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:        0x100f27095 - core::result::unwrap_failed::h2a0ffdcdbffb9262
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
  16:        0x100cfe2b1 - <redb::tree_store::page_store::page_manager::TransactionalMemory as core::ops::drop::Drop>::drop::he903d6dc884610b5
  17:        0x100cd93b3 - core::ptr::drop_in_place<redb::tree_store::page_store::page_manager::TransactionalMemory>::h7f417c43540bfe0c
  18:        0x100cdafa1 - redb::db::Database::new::hf79b01edd109b852
  19:        0x100738cd9 - redb::db::Builder::open_mmapped::ha4414c39c49df8bd
  20:        0x100a57381 - ord::index::Index::open::h9cc6f2081b376cdb
  21:        0x1007b4ef2 - ord::subcommand::index::run::h74a10a8980533b0d
  22:        0x100a00847 - ord::subcommand::Subcommand::run::hac8bca658950d312
  23:        0x1008d1486 - ord::main::ha767843f454048d8
  24:        0x1006fdcb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::he7c5919472da9bc8
  25:        0x1006fdc8c - std::rt::lang_start::{{closure}}::h7c949b917fc708c3
  26:        0x100ec6364 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2302f1d25ef2ca9b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  27:        0x100ec6364 - std::panicking::try::do_call::h6695e32a593de2cc
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  28:        0x100ec6364 - std::panicking::try::hd4a93095627721a9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  29:        0x100ec6364 - std::panic::catch_unwind::he41b3dba63feca94
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  30:        0x100ec6364 - std::rt::lang_start_internal::{{closure}}::hbf45583011495a61
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  31:        0x100ec6364 - std::panicking::try::do_call::ha3e6b3edab7da449
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  32:        0x100ec6364 - std::panicking::try::hd4e0f354bf7022b9
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  33:        0x100ec6364 - std::panic::catch_unwind::h1035b163871a4269
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  34:        0x100ec6364 - std::rt::lang_start_internal::hd56d2fa7efb2dd60
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  35:        0x1006fdcfc - _main
  36:     0x7ff816e81310 - <unknown>
thread panicked while panicking. aborting.
zsh: abort      RUST_BACKTRACE=full ord --first-inscription-height 767430 --height-limit
```

**Comment by cberner** [comment]
How many blocks did it index before it crashed?

**Comment by AdrianScott** [comment]
for me, 355896

**Comment by cberner** [comment]
@hantuzun are you able to reproduce this? I tried on my Linux desktop and have not been able to, so it might be something OSX specific.

@AdrianScott 's issue appears to be an out of space issue and probably isn't related to your crash

**Comment by cberner** [comment]
Going to close this, but feel free to re-open if you have more info on how to reproduce it.
