### ISSUE TITLE
Panic opening after disk fills up

### ISSUE THREAD

**Issue by lhallam** [cberner/redb#620]
After running out of disk space while writing to the database, opening it panics:

```
│ thread '<unnamed>' panicked at 'assertion failed: `(left == right)`                                                                   │
│   left: `1`,                                                                                                                          │
│  right: `0`', /home/xal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.0/src/tree_store/page_store/region.rs:312:9     │
│ stack backtrace:                                                                                                                      │
│    0: rust_begin_unwind                                                                                                               │
│              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5                                    │
│    1: core::panicking::panic_fmt                                                                                                      │
│              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14                                   │
│    2: core::panicking::assert_failed_inner                                                                                            │
│    3: core::panicking::assert_failed                                                                                                  │
│    4: redb::tree_store::page_store::region::Allocators::from_bytes                                                                    │
│    5: redb::tree_store::page_store::page_manager::InMemoryState::from_bytes                                                           │
│    6: redb::tree_store::page_store::page_manager::TransactionalMemory::new                                                            │
│    7: redb::db::Database::new                                                                                                         │
│    8: redb::db::Builder::open                                                                                                         │
│ note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                               │
```

**Comment by cberner** [comment]
Can you try calling `Database::check_integrity()` and let me know if the panic goes away? I have a theory about how it got into this state, but I haven't replicated the issue yet
