### ISSUE TITLE
Crash on startup after multiple runs

### ISSUE THREAD

**Issue by asonix** [cberner/redb#629]
I was trying to create a minimum reproduction for a different data corruption issue i've been having when playing with redb, but found this instead.

reproduction:
```rust
const TABLE: redb::MultimapTableDefinition<'static, u128, u128> =
    redb::MultimapTableDefinition::new("some-table");

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = redb::Database::create("db.redb")?;
    db.check_integrity()?;

    let txn = db.begin_write()?;
    let mut table = txn.open_multimap_table(TABLE)?;

    for i in 0..1024 {
        table.insert(0, i)?;
    }
    drop(table);

    txn.commit()?;

    Ok(())
}
```

error:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1089536`,
 right: `1589248`', /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.2/src/tree_store/page_store/page_manager.rs:244:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /build/rustc-1.70.0-src/library/core/src/panicking.rs:228:5
   4: redb::tree_store::page_store::page_manager::TransactionalMemory::new
             at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.2/src/tree_store/page_store/page_manager.rs:244:9
   5: redb::db::Database::new
             at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.2/src/db.rs:569:23
   6: redb::db::Builder::create
             at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.2/src/db.rs:746:9
   7: redb::db::Database::create
             at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.2/src/db.rs:249:9
   8: redb_bug::main
             at ./src/main.rs:5:18
   9: core::ops::function::FnOnce::call_once
             at /build/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by asonix** [comment]
It doesn't crash on the first run or the second run, but seems to always crash on the third run when opening the database

**Comment by cberner** [comment]
Thanks for the simple repro! I'll take a look this weekend

**Comment by paulirotta** [comment]
Same thing. Here is another simple example. If `compact()` is called after check_integrity(), it fails as above on the 2nd start instead of 3rd.

```
use redb::{Database, Error, ReadableTable, TableDefinition};

const TABLE: TableDefinition<&str, u64> = TableDefinition::new("my_data");

fn main() -> Result<(), Error> {
    let mut db = Database::create("my_db.redb")?;
    let _ = db.check_integrity()?;
    // let _ = db.compact()?;
    let write_txn = db.begin_write()?;
    {
        let mut table = write_txn.open_table(TABLE)?;
        table.insert("my_key", &123)?;
    }
    write_txn.commit()?;

    let read_txn = db.begin_read()?;
    let table = read_txn.open_table(TABLE)?;
    assert_eq!(table.get("my_key")?.unwrap().value(), 123);

    Ok(())
}
```

**Comment by cberner** [comment]
Fix turned out to be pretty easy. I believe the attached PR will solve both these cases
