### ISSUE TITLE
Panic from use of drain

### ISSUE THREAD

**Issue by asonix** [cberner/redb#631]
Reproduction:
```rust
const TABLE: redb::TableDefinition<'static, u128, u128> = redb::TableDefinition::new("table");

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = redb::Database::create("db.redb")?;
    db.check_integrity()?;

    let txn = db.begin_write()?;
    let mut table = txn.open_table(TABLE)?;

    for i in 0..1024 {
        table.insert(i, i)?;
    }

    table.drain(128..256)?;

    drop(table);
    txn.commit()?;

    Ok(())
}
```

Error:
```
thread 'main' panicked at 'assertion failed: !self.read_page_ref_counts.lock().unwrap().contains_key(&page_number)', /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.3/src/tree_store/page_sto
re/page_manager.rs:689:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.3/src/tree_store/btree.rs:274:30
stack backtrace:
   0:     0x564e6c1e552a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had616a77c932ab1b
   1:     0x564e6c20502f - core::fmt::write::h3a35c0754863b3d5
   2:     0x564e6c1f0705 - std::io::Write::write_fmt::h502c0f36b9ea0da9
   3:     0x564e6c1e52e5 - std::sys_common::backtrace::print::h90cd8adaf174c598
   4:     0x564e6c1ea49e - std::panicking::default_hook::{{closure}}::ha88f96a3c80996f9
   5:     0x564e6c1ea159 - std::panicking::default_hook::haf5a79a7bf67f396
   6:     0x564e6c1ea9f1 - std::panicking::rust_panic_with_hook::h69ad028564cd3ed4
   7:     0x564e6c1e5859 - std::panicking::begin_panic_handler::{{closure}}::h8ea911da5e199679
   8:     0x564e6c1e5636 - std::sys_common::backtrace::__rust_end_short_backtrace::h02258dadc83c0b77
   9:     0x564e6c1ea6f2 - rust_begin_unwind
  10:     0x564e6c0bd4e3 - core::panicking::panic_fmt::h55a49ce1199dc412
  11:     0x564e6c0bd423 - core::result::unwrap_failed::h785f5d4e4bc45da6
  12:     0x564e6c0f65d9 - core::result::Result<T,E>::unwrap::h8080bbb8c633e891
                               at /build/rustc-1.70.0-src/library/core/src/result.rs:1089:23
  13:     0x564e6c0c67d6 - redb::tree_store::btree::BtreeMut<K,V>::get_root::hffd0b85b039d1ee5
                               at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.3/src/tree_store/btree.rs:274:10
  14:     0x564e6c0c0db7 - redb::transactions::WriteTransaction::close_table::h69cf7aa4eeebb9d8
                               at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.3/src/transactions.rs:664:48
  15:     0x564e6c0c9e69 - <redb::table::Table<K,V> as core::ops::drop::Drop>::drop::h96bdf1ccb7c27865
                               at /home/asonix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.0.3/src/table.rs:195:9
  16:     0x564e6c0c9a43 - core::ptr::drop_in_place<redb::table::Table<u128,u128>>::h2d8ccecb74a15e60
                               at /build/rustc-1.70.0-src/library/core/src/ptr/mod.rs:490:1
  17:     0x564e6c0c90bd - redb_bug::main::h4f08d742e18abf63
                               at /home/asonix/Development/rust/redb-bug/src/main.rs:20:1
  18:     0x564e6c0c982b - core::ops::function::FnOnce::call_once::h356e60869536e18b
                               at /build/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
  19:     0x564e6c0c97ae - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c6f54fa27bc7885
                               at /build/rustc-1.70.0-src/library/std/src/sys_common/backtrace.rs:134:18
  20:     0x564e6c0bdf81 - std::rt::lang_start::{{closure}}::h06593bf157a2248b
                               at /build/rustc-1.70.0-src/library/std/src/rt.rs:166:18
  21:     0x564e6c1ea5f1 - std::panicking::try::h2fded24329a9b820
  22:     0x564e6c1d82ab - std::rt::lang_start_internal::hbbe6eb94b9b031b1
  23:     0x564e6c0bdf5a - std::rt::lang_start::h9ce76516ba373bf7
                               at /build/rustc-1.70.0-src/library/std/src/rt.rs:165:17
  24:     0x564e6c0c913e - main
  25:     0x7ff67474cace - __libc_start_call_main
  26:     0x7ff67474cb89 - __libc_start_main@@GLIBC_2.34
  27:     0x564e6c0bd975 - _start
  28:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

**Comment by asonix** [comment]
it has a much uglier error when running in release mode, too

**Comment by cberner** [comment]
Thanks for the repro! Ya, I see what the problem is. `drain()` isn't tested by the fuzzer, and I missed that there's a serious bug in its implementation
