### ISSUE TITLE
Panic with TryFromIntError

### ISSUE THREAD

**Issue by casey** [cberner/redb#719]
I'm getting a reproducible panic on [this branch of ord](https://github.com/casey/ord/tree/index-by-sequence-number) that looks to be coming from inside of redb. I was able to reproduce it with redb 1.3.0 through 1.0.0. This branch changes a bunch of database keys and values from `[u8;32]` to `u32`, so this might have to do with having a bunch of small keys/values packed into pages.

To reproduce:

```
cargo run index update
```

It takes about 25 minutes on my machine before it crashes, always at height 777074. There are two backtraces below, I believe because of a panic during unwinding, which triggers another backtrace and aborts the program.

<details>
<summary>Backtrace</summary>

```
[indexing blocks] ████████████████████████████████████████████████████████████████████████████████████░░░░░ 777074/816683
thread 'main' panicked at /Users/rodarmor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.3.0/src/tree_store/btree_base.rs:851:60:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: redb::tree_store::btree_base::LeafMutator::insert
   4: redb::tree_store::btree_mutator::MutateHelper<K,V>::insert_helper
   5: redb::tree_store::btree_mutator::MutateHelper<K,V>::insert_helper
   6: redb::tree_store::btree_mutator::MutateHelper<K,V>::insert
   7: redb::tree_store::btree::BtreeMut<K,V>::insert
   8: ord::index::updater::inscription_updater::InscriptionUpdater::update_inscription_location
   9: ord::index::updater::inscription_updater::InscriptionUpdater::index_envelopes
  10: ord::index::updater::Updater::update_index
  11: ord::index::Index::update
  12: ord::arguments::Arguments::run
  13: ord::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /Users/rodarmor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.3.0/src/tree_store/btree.rs:279:30:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:        0x104dadf7c - std::backtrace_rs::backtrace::libunwind::trace::h815672f5996c9e34
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104dadf7c - std::backtrace_rs::backtrace::trace_unsynchronized::h2e094b2d8c270437
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104dadf7c - std::sys_common::backtrace::_print_fmt::hae24b71afea95695
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104dadf7c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104dd0698 - core::fmt::rt::Argument::fmt::h835101b6de0df17f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:        0x104dd0698 - core::fmt::write::h5d55d44549819258
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:        0x104daa638 - std::io::Write::write_fmt::hc515897f91abd6cf
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:        0x104daddbc - std::sys_common::backtrace::_print::h5844dab5cfa39fca
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x104daddbc - std::sys_common::backtrace::print::h2c300c1ebedfc73c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x104daf41c - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:        0x104daf148 - std::panicking::default_hook::h2c0ef097934ee9e6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:        0x104daf964 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:        0x104daf870 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:        0x104dae408 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x104daf5d4 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:        0x104e04ae0 - core::panicking::panic_fmt::h9072a0246ecafd14
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:        0x104e04e08 - core::result::unwrap_failed::hd7600d03a3086be4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:        0x104663c4c - redb::transactions::WriteTransaction::close_table::h178624aa7ceca618
  18:        0x104623f9c - core::ptr::drop_in_place<redb::table::Table<i32,u32>>::hba34a026d370cdd9
  19:        0x10463e45c - ord::index::updater::Updater::update_index::hf0bea45124687d1f
  20:        0x1048d4f24 - ord::index::Index::update::h93ffda8104dd1c37
  21:        0x104633800 - ord::arguments::Arguments::run::h9dc11cabcab3b053
  22:        0x104973dec - ord::main::hb58e5bf9b507346c
  23:        0x1045c408c - std::sys_common::backtrace::__rust_begin_short_backtrace::h7f449d97fa92a7f4
  24:        0x1045c40a4 - std::rt::lang_start::{{closure}}::h6ac9ff54b341975a
  25:        0x104da33b4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7fff7c88c61df16f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  26:        0x104da33b4 - std::panicking::try::do_call::h5c3526811781b4da
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  27:        0x104da33b4 - std::panicking::try::h64cb573047f67390
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  28:        0x104da33b4 - std::panic::catch_unwind::h0ee316aa6f14634c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  29:        0x104da33b4 - std::rt::lang_start_internal::{{closure}}::hbd896cc316ba7338
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  30:        0x104da33b4 - std::panicking::try::do_call::hbae6886803fae47e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  31:        0x104da33b4 - std::panicking::try::hcc0fbb3995231d31
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  32:        0x104da33b4 - std::panic::catch_unwind::hf36acbaf210582be
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  33:        0x104da33b4 - std::rt::lang_start_internal::hadaf077a6dd0140b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  34:        0x1045c4108 - _main
thread 'main' panicked at library/core/src/panicking.rs:126:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x104dadf7c - std::backtrace_rs::backtrace::libunwind::trace::h815672f5996c9e34
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x104dadf7c - std::backtrace_rs::backtrace::trace_unsynchronized::h2e094b2d8c270437
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104dadf7c - std::sys_common::backtrace::_print_fmt::hae24b71afea95695
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104dadf7c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104dd0698 - core::fmt::rt::Argument::fmt::h835101b6de0df17f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:        0x104dd0698 - core::fmt::write::h5d55d44549819258
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:        0x104daa638 - std::io::Write::write_fmt::hc515897f91abd6cf
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:        0x104daddbc - std::sys_common::backtrace::_print::h5844dab5cfa39fca
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x104daddbc - std::sys_common::backtrace::print::h2c300c1ebedfc73c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x104daf41c - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:        0x104daf148 - std::panicking::default_hook::h2c0ef097934ee9e6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:        0x104daf964 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:        0x104daf834 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:        0x104dae408 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x104daf5d4 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:        0x104e04b10 - core::panicking::panic_nounwind_fmt::ha4f6bbf8fe9fb5ae
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:96:14
  16:        0x104e04b8c - core::panicking::panic_nounwind::ha756411eedbc9594
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:126:5
  17:        0x104e04bfc - core::panicking::panic_cannot_unwind::h496677c8c27b4397
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:189:5
  18:        0x10463e4c0 - ord::index::updater::Updater::update_index::hf0bea45124687d1f
  19:        0x1048d4f24 - ord::index::Index::update::h93ffda8104dd1c37
  20:        0x104633800 - ord::arguments::Arguments::run::h9dc11cabcab3b053
  21:        0x104973dec - ord::main::hb58e5bf9b507346c
  22:        0x1045c408c - std::sys_common::backtrace::__rust_begin_short_backtrace::h7f449d97fa92a7f4
  23:        0x1045c40a4 - std::rt::lang_start::{{closure}}::h6ac9ff54b341975a
  24:        0x104da33b4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7fff7c88c61df16f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  25:        0x104da33b4 - std::panicking::try::do_call::h5c3526811781b4da
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  26:        0x104da33b4 - std::panicking::try::h64cb573047f67390
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  27:        0x104da33b4 - std::panic::catch_unwind::h0ee316aa6f14634c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  28:        0x104da33b4 - std::rt::lang_start_internal::{{closure}}::hbd896cc316ba7338
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  29:        0x104da33b4 - std::panicking::try::do_call::hbae6886803fae47e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  30:        0x104da33b4 - std::panicking::try::hcc0fbb3995231d31
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  31:        0x104da33b4 - std::panic::catch_unwind::hf36acbaf210582be
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  32:        0x104da33b4 - std::rt::lang_start_internal::hadaf077a6dd0140b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  33:        0x1045c4108 - _main
thread caused non-unwinding panic. aborting.
```

</details>

**Comment by casey** [comment]
It looks like it does have to do with small and or numerous keys/values. I was able to reproduce it with:

```rust
use redb::{Database, TableDefinition};

const TABLE: TableDefinition<u32, u32> = TableDefinition::new("TABLE");

fn main() {
    let database = Database::builder().create("database.redb").unwrap();

    let wtx = database.begin_write().unwrap();

    let mut table = wtx.open_table(TABLE).unwrap();

    for i in 0..100_000_000 {
        table.insert(i, i).unwrap();

        if i % 100_000 == 0 {
            eprintln!("{i}");
        }
    }

    drop(table);

    wtx.commit().unwrap();
}
```

It panics somewhere between the 100,000th and 200,000th insertion.

**Comment by casey** [comment]
Very interesting!

If you replace `TableDefinition<u32, u32>` with `TableDefinition<u64, u64>` it doesn't crash, and it also runs much more quickly, taking 6 seconds with u32s, vs 0.25 seconds with u64s, even though you would expect it to take longer with larger keys and values.

**Comment by cberner** [comment]
Well that's bad. Looking!

**Comment by casey** [comment]
What a Chad! Awesome.
